### ISSUE TITLE
suggest change to a table with date, type

### ISSUE THREAD

**Issue by Eisenh** [hemanth/awesome-pwa#116]
This is an excellent resource, thanks!
Is there a chance the list could have dates added to each entry?  It is a fast moving field.  It would be great if the table had fields for the url, date found or updated, type (as in the current categories).
I am finding that many articles from 2016, 2017 do not reflect current best practices, and it is tiresome to check each link to see the date.

**Comment by mjswensen** [comment]
This is a great idea. Closing the issue for now but feel free to open a PR to add this information if desired.
