### ISSUE TITLE
The Session doesn't use SW. Remove?

### ISSUE THREAD

**Issue by owencm** [hemanth/awesome-pwa#14]
I was looking at The Session today - I don't seem to be able to see it registering a SW or doing anything offline. 

It doesn't seem like a PWA to me, I'd suggest we remove it.

**Comment by hemanth** [comment]
Which one?

**Comment by addyosmani** [comment]
Hmm. Not seeing the Session listed here. I wonder if @owencm was referring to it being on pwa.rocks
