### ISSUE TITLE
Add apps: Lofimusic.app and Murlok.io

### ISSUE THREAD

**Issue by maxence-charriere** [hemanth/awesome-pwa#170]
Hello there,
It's a wonderful idea to have a place to reference PWA's!

I'm myself the author of 2:
- [Lofimusic.app](https://lofimusic.app): a PWA that lists and play Lo-Fi radios
- [Murlok.io](https://murlok.io): a PWA that provide character guides for World of Warcraft

Could it be possible to add those 2 ones to the list?

Best,
Maxence.

**Comment by mjswensen** [comment]
Hi @maxence-charriere ,

Excellent work on your apps! Yes, we'd be happy to add them to the list—if you open a pull request that modifies the readme, adding your apps to the appropriate section in alphabetical order, we'll happily merge it. Thank you!
