### ISSUE TITLE
Please add LoremGenerator.io and CoolTextGenerator.io to the list

### ISSUE THREAD

**Issue by 684efs3** [hemanth/awesome-pwa#201]

**Comment by mjswensen** [comment]
Hi @684efs3 , neither of the submissions appear to be Progressive Web Apps:

![image](https://user-images.githubusercontent.com/1591879/118130336-7b5e5200-b3ba-11eb-862d-3fb278e1199c.png)

![image](https://user-images.githubusercontent.com/1591879/118130400-8b763180-b3ba-11eb-888d-6f6ea89c8b52.png)

Please re-open this issue if that's not the case.
