### ISSUE TITLE
Verify link

### ISSUE THREAD

**Issue by evansantos** [hemanth/awesome-pwa#21]
What do you think about adding [Awesome bot](https://github.com/dkhamsing/awesome_bot)?

![disney-thumbs-up-mickey-mouse-U7KLMsMziNQB2](https://camo.githubusercontent.com/5de37f7ab029c7790011249969ae261fc6066ad2/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f55374b4c4d734d7a694e5142322f67697068792e676966>)

**Comment by hemanth** [comment]
Nice, PR welcomed! 
![one-direction-perfect-l41lKmDyZJtTVPThK](https://camo.githubusercontent.com/3b35f44c6b22d51f3f2e9fee14f6dac72d9e1b0a/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6c34316c4b6d44795a4a7454565054684b2f67697068792e676966>)

**Comment by evansantos** [comment]
I'll be adding then :D 
Thanks, @hemanth

**Comment by hemanth** [comment]
Echo...

**Comment by evansantos** [comment]
@hemanth sorry for taking to long! 
I had forget this wasn't done yet! 

![angeles-bachcaps-bearfighting-RFDXes97gboYg](https://camo.githubusercontent.com/bbfe3a21b9989e90e60eec6c6d85ba46dbcd4db3/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f524644586573393767626f59672f67697068792e676966>)

**Comment by hemanth** [comment]
![mst3k-the-pod-people-toy-robot-fAAJlhMB1wU92](https://camo.githubusercontent.com/caac9183fe8709c4daaf5cd352c7f6100641938e/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f6641414a6c684d4231775539322f67697068792e676966>)

**Comment by evansantos** [comment]
Do you want that i add the badge?

**Comment by hemanth** [comment]
Better!

**Comment by hemanth** [comment]
Travis [cries](https://travis-ci.org/hemanth/awesome-pwa#L282) the links seems fine, looks like, it's bombing in `HTTPS` cert error.

**Comment by evansantos** [comment]
@hemanth I'll whitelist it
