### ISSUE TITLE
Section for Push Notifications maybe?

### ISSUE THREAD

**Issue by sameoldmadness** [hemanth/awesome-pwa#24]
I'd like to make a PR with a couple of links related to Push Notifications API: tutorials, specs, libraries, blog posts.

Wouldn't it be handy to keep them in one place, or should I put them into existing sections?

**Comment by hemanth** [comment]
Sorry for the late reply, please put them in the existing sections.

**Comment by sameoldmadness** [comment]
Okay, thanks for reply.
