### ISSUE TITLE
New PWA, Freefy

### ISSUE THREAD

**Issue by alvaroadlf** [hemanth/awesome-pwa#274]
Hi,

Would it be possible to add Freefy? [https://freefy.app](https://freefy.app), it's a free service and works as a PWA.

Thanks,
Regards

**Comment by mjswensen** [comment]
Unfortunately it appears that the app is no longer available:

<img width="921" alt="image" src="https://github.com/hemanth/awesome-pwa/assets/1591879/e81c3ac3-c77d-4d62-8028-47458404df97">

Once fixed, feel free to open a pull request adding it to the README.

**Comment by alvaroadlf** [comment]
Sorry but the app is still available, check it again please its was a punctual downtime

**Comment by mjswensen** [comment]
We'd be happy to add it @alvaroadlf , please open a pull request to add it to the README 👍
