### ISSUE TITLE
Add an Expo e-commerce complete project

### ISSUE THREAD

**Issue by huanghanzhilian** [hemanth/awesome-pwa#300]
C-Shopping-RN APP

This is a complete App developed by React Native (Expo). It is a beautiful e-commerce shopping application.

## Use technology

- React Native
- Redux Toolkit
- RTK Query
- Expo Router
-NativeWind

App open source address: https://github.com/huanghanzhilian/c-shopping-rn
Full stack open source address: https://github.com/huanghanzhilian/c-shopping

**Comment by mjswensen** [comment]
@huanghanzhilian , this repository is for [progressive web apps](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps), which are subtly different than native apps built with web technologies.
