### ISSUE TITLE
Acceptance Criteria

### ISSUE THREAD

**Issue by developit** [hemanth/awesome-pwa#4]
@hemanth: are there guidelines for what will be accepted into this list? Curious if I could submit [esbench.com](http://esbench.com). Thanks!

**Comment by hemanth** [comment]
I feel any site with: ATHS, Offline-support (Indeed with sw), splash screen, with decent app icons must be fine :)

**Comment by developit** [comment]
Perfect thanks. Looks like I need to add offline support, haha.

**Comment by hemanth** [comment]
:+1:
