### ISSUE TITLE
Add these to the list! 

### ISSUE THREAD

**Issue by hemanth** [hemanth/awesome-pwa#6]
* Dev.Opera
* Oumy
* Airhorner
* Medium
* Twitter
* svgomg
* Voice Memos
* Guitar Tuner
* abc.xyz

**Comment by vigneshshanmugam** [comment]
What about this one?  https://jakearchibald-gcm.appspot.com/

**Comment by hemanth** [comment]
Yes.

**Comment by mayankchd** [comment]
This one also https://github.com/nolanlawson/pokedex.org

**Comment by hemanth** [comment]
Cool, PRs are welcomed ;)

**Comment by kenchris** [comment]
https://weneed-1147.appspot.com :-)

**Comment by justinribeiro** [comment]
https://sv-ginger.appspot.com

**Comment by PaulKinlan** [comment]
Wiki Offline  https://wiki-offline.jakearchibald.com/

**Comment by hemanth** [comment]
Thanks for the links.

Was planning to add gifs for all of them but on a second thought I will just create a list for now.

**Comment by vigneshshanmugam** [comment]
Check this out - https://operasoftware.github.io/pwa-list/

**Comment by hemanth** [comment]
Nice, that came in like a day ago ;)

This repo is like almost a month old ;)

**Comment by vigneshshanmugam** [comment]
Yeah true :)
